// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: protos/users_musics_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowArtistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistId string `protobuf:"bytes,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
}

func (x *FollowArtistRequest) Reset() {
	*x = FollowArtistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowArtistRequest) ProtoMessage() {}

func (x *FollowArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowArtistRequest.ProtoReflect.Descriptor instead.
func (*FollowArtistRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{0}
}

func (x *FollowArtistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowArtistRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

type UnfollowArtistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistId string `protobuf:"bytes,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
}

func (x *UnfollowArtistRequest) Reset() {
	*x = UnfollowArtistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnfollowArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowArtistRequest) ProtoMessage() {}

func (x *UnfollowArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowArtistRequest.ProtoReflect.Descriptor instead.
func (*UnfollowArtistRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{1}
}

func (x *UnfollowArtistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnfollowArtistRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

type GetFollowingArtistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistId string `protobuf:"bytes,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
}

func (x *GetFollowingArtistRequest) Reset() {
	*x = GetFollowingArtistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFollowingArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingArtistRequest) ProtoMessage() {}

func (x *GetFollowingArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingArtistRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingArtistRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowingArtistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowingArtistRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

type GetAllFollowingArtistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAllFollowingArtistsRequest) Reset() {
	*x = GetAllFollowingArtistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFollowingArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFollowingArtistsRequest) ProtoMessage() {}

func (x *GetAllFollowingArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFollowingArtistsRequest.ProtoReflect.Descriptor instead.
func (*GetAllFollowingArtistsRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllFollowingArtistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FollowingArtist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistId string `protobuf:"bytes,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
}

func (x *FollowingArtist) Reset() {
	*x = FollowingArtist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowingArtist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowingArtist) ProtoMessage() {}

func (x *FollowingArtist) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowingArtist.ProtoReflect.Descriptor instead.
func (*FollowingArtist) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{4}
}

func (x *FollowingArtist) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowingArtist) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

type FollowingArtists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistsId []string `protobuf:"bytes,2,rep,name=artists_id,json=artistsId,proto3" json:"artists_id,omitempty"`
}

func (x *FollowingArtists) Reset() {
	*x = FollowingArtists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowingArtists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowingArtists) ProtoMessage() {}

func (x *FollowingArtists) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowingArtists.ProtoReflect.Descriptor instead.
func (*FollowingArtists) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{5}
}

func (x *FollowingArtists) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowingArtists) GetArtistsId() []string {
	if x != nil {
		return x.ArtistsId
	}
	return nil
}

type ViewMusicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MusicId string `protobuf:"bytes,2,opt,name=music_id,json=musicId,proto3" json:"music_id,omitempty"`
}

func (x *ViewMusicRequest) Reset() {
	*x = ViewMusicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewMusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMusicRequest) ProtoMessage() {}

func (x *ViewMusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMusicRequest.ProtoReflect.Descriptor instead.
func (*ViewMusicRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{6}
}

func (x *ViewMusicRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ViewMusicRequest) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

type GetViewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MusicId string `protobuf:"bytes,2,opt,name=music_id,json=musicId,proto3" json:"music_id,omitempty"`
}

func (x *GetViewsRequest) Reset() {
	*x = GetViewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewsRequest) ProtoMessage() {}

func (x *GetViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewsRequest.ProtoReflect.Descriptor instead.
func (*GetViewsRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetViewsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetViewsRequest) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

type GetLastViewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetLastViewsRequest) Reset() {
	*x = GetLastViewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastViewsRequest) ProtoMessage() {}

func (x *GetLastViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastViewsRequest.ProtoReflect.Descriptor instead.
func (*GetLastViewsRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetLastViewsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLastViewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMostViewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetMostViewsRequest) Reset() {
	*x = GetMostViewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMostViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostViewsRequest) ProtoMessage() {}

func (x *GetMostViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostViewsRequest.ProtoReflect.Descriptor instead.
func (*GetMostViewsRequest) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetMostViewsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMostViewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserMusic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MusicId string `protobuf:"bytes,2,opt,name=music_id,json=musicId,proto3" json:"music_id,omitempty"`
	Views   int64  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
}

func (x *UserMusic) Reset() {
	*x = UserMusic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMusic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMusic) ProtoMessage() {}

func (x *UserMusic) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMusic.ProtoReflect.Descriptor instead.
func (*UserMusic) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{10}
}

func (x *UserMusic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMusic) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

func (x *UserMusic) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

type UserMusicsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserMusics []*UserMusic `protobuf:"bytes,1,rep,name=user_musics,json=userMusics,proto3" json:"user_musics,omitempty"`
}

func (x *UserMusicsList) Reset() {
	*x = UserMusicsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMusicsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMusicsList) ProtoMessage() {}

func (x *UserMusicsList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMusicsList.ProtoReflect.Descriptor instead.
func (*UserMusicsList) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{11}
}

func (x *UserMusicsList) GetUserMusics() []*UserMusic {
	if x != nil {
		return x.UserMusics
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_users_musics_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_musics_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_users_musics_service_proto_rawDescGZIP(), []int{12}
}

var File_protos_users_musics_service_proto protoreflect.FileDescriptor

var file_protos_users_musics_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x13, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x15, 0x55, 0x6e, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x0f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x10,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x10, 0x56, 0x69, 0x65, 0x77,
	0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64,
	0x22, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x44, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x55, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22, 0x43, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0b,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75,
	0x73, 0x69, 0x63, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xb2, 0x04, 0x0a, 0x0b, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0e, 0x55, 0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x09, 0x56, 0x69, 0x65, 0x77, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x56, 0x69,
	0x65, 0x77, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x0c, 0x5a,
	0x0a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_users_musics_service_proto_rawDescOnce sync.Once
	file_protos_users_musics_service_proto_rawDescData = file_protos_users_musics_service_proto_rawDesc
)

func file_protos_users_musics_service_proto_rawDescGZIP() []byte {
	file_protos_users_musics_service_proto_rawDescOnce.Do(func() {
		file_protos_users_musics_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_users_musics_service_proto_rawDescData)
	})
	return file_protos_users_musics_service_proto_rawDescData
}

var file_protos_users_musics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_users_musics_service_proto_goTypes = []interface{}{
	(*FollowArtistRequest)(nil),           // 0: proto.FollowArtistRequest
	(*UnfollowArtistRequest)(nil),         // 1: proto.UnfollowArtistRequest
	(*GetFollowingArtistRequest)(nil),     // 2: proto.GetFollowingArtistRequest
	(*GetAllFollowingArtistsRequest)(nil), // 3: proto.GetAllFollowingArtistsRequest
	(*FollowingArtist)(nil),               // 4: proto.FollowingArtist
	(*FollowingArtists)(nil),              // 5: proto.FollowingArtists
	(*ViewMusicRequest)(nil),              // 6: proto.ViewMusicRequest
	(*GetViewsRequest)(nil),               // 7: proto.GetViewsRequest
	(*GetLastViewsRequest)(nil),           // 8: proto.GetLastViewsRequest
	(*GetMostViewsRequest)(nil),           // 9: proto.GetMostViewsRequest
	(*UserMusic)(nil),                     // 10: proto.UserMusic
	(*UserMusicsList)(nil),                // 11: proto.UserMusicsList
	(*Empty)(nil),                         // 12: proto.Empty
}
var file_protos_users_musics_service_proto_depIdxs = []int32{
	10, // 0: proto.UserMusicsList.user_musics:type_name -> proto.UserMusic
	0,  // 1: proto.UsersMusics.FollowArtist:input_type -> proto.FollowArtistRequest
	1,  // 2: proto.UsersMusics.UnfollowArtist:input_type -> proto.UnfollowArtistRequest
	2,  // 3: proto.UsersMusics.GetFollowingArtist:input_type -> proto.GetFollowingArtistRequest
	3,  // 4: proto.UsersMusics.GetAllFollowingArtists:input_type -> proto.GetAllFollowingArtistsRequest
	6,  // 5: proto.UsersMusics.ViewMusic:input_type -> proto.ViewMusicRequest
	7,  // 6: proto.UsersMusics.GetViews:input_type -> proto.GetViewsRequest
	8,  // 7: proto.UsersMusics.GetLastViews:input_type -> proto.GetLastViewsRequest
	9,  // 8: proto.UsersMusics.GetMostViews:input_type -> proto.GetMostViewsRequest
	12, // 9: proto.UsersMusics.FollowArtist:output_type -> proto.Empty
	12, // 10: proto.UsersMusics.UnfollowArtist:output_type -> proto.Empty
	4,  // 11: proto.UsersMusics.GetFollowingArtist:output_type -> proto.FollowingArtist
	5,  // 12: proto.UsersMusics.GetAllFollowingArtists:output_type -> proto.FollowingArtists
	10, // 13: proto.UsersMusics.ViewMusic:output_type -> proto.UserMusic
	10, // 14: proto.UsersMusics.GetViews:output_type -> proto.UserMusic
	11, // 15: proto.UsersMusics.GetLastViews:output_type -> proto.UserMusicsList
	11, // 16: proto.UsersMusics.GetMostViews:output_type -> proto.UserMusicsList
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_protos_users_musics_service_proto_init() }
func file_protos_users_musics_service_proto_init() {
	if File_protos_users_musics_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_users_musics_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowArtistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnfollowArtistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFollowingArtistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFollowingArtistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowingArtist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowingArtists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewMusicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastViewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMostViewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMusic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMusicsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_users_musics_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_users_musics_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_users_musics_service_proto_goTypes,
		DependencyIndexes: file_protos_users_musics_service_proto_depIdxs,
		MessageInfos:      file_protos_users_musics_service_proto_msgTypes,
	}.Build()
	File_protos_users_musics_service_proto = out.File
	file_protos_users_musics_service_proto_rawDesc = nil
	file_protos_users_musics_service_proto_goTypes = nil
	file_protos_users_musics_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UsersMusicsClient is the client API for UsersMusics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersMusicsClient interface {
	FollowArtist(ctx context.Context, in *FollowArtistRequest, opts ...grpc.CallOption) (*Empty, error)
	UnfollowArtist(ctx context.Context, in *UnfollowArtistRequest, opts ...grpc.CallOption) (*Empty, error)
	GetFollowingArtist(ctx context.Context, in *GetFollowingArtistRequest, opts ...grpc.CallOption) (*FollowingArtist, error)
	GetAllFollowingArtists(ctx context.Context, in *GetAllFollowingArtistsRequest, opts ...grpc.CallOption) (*FollowingArtists, error)
	ViewMusic(ctx context.Context, in *ViewMusicRequest, opts ...grpc.CallOption) (*UserMusic, error)
	GetViews(ctx context.Context, in *GetViewsRequest, opts ...grpc.CallOption) (*UserMusic, error)
	GetLastViews(ctx context.Context, in *GetLastViewsRequest, opts ...grpc.CallOption) (*UserMusicsList, error)
	GetMostViews(ctx context.Context, in *GetMostViewsRequest, opts ...grpc.CallOption) (*UserMusicsList, error)
}

type usersMusicsClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersMusicsClient(cc grpc.ClientConnInterface) UsersMusicsClient {
	return &usersMusicsClient{cc}
}

func (c *usersMusicsClient) FollowArtist(ctx context.Context, in *FollowArtistRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/FollowArtist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersMusicsClient) UnfollowArtist(ctx context.Context, in *UnfollowArtistRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/UnfollowArtist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersMusicsClient) GetFollowingArtist(ctx context.Context, in *GetFollowingArtistRequest, opts ...grpc.CallOption) (*FollowingArtist, error) {
	out := new(FollowingArtist)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/GetFollowingArtist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersMusicsClient) GetAllFollowingArtists(ctx context.Context, in *GetAllFollowingArtistsRequest, opts ...grpc.CallOption) (*FollowingArtists, error) {
	out := new(FollowingArtists)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/GetAllFollowingArtists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersMusicsClient) ViewMusic(ctx context.Context, in *ViewMusicRequest, opts ...grpc.CallOption) (*UserMusic, error) {
	out := new(UserMusic)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/ViewMusic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersMusicsClient) GetViews(ctx context.Context, in *GetViewsRequest, opts ...grpc.CallOption) (*UserMusic, error) {
	out := new(UserMusic)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/GetViews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersMusicsClient) GetLastViews(ctx context.Context, in *GetLastViewsRequest, opts ...grpc.CallOption) (*UserMusicsList, error) {
	out := new(UserMusicsList)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/GetLastViews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersMusicsClient) GetMostViews(ctx context.Context, in *GetMostViewsRequest, opts ...grpc.CallOption) (*UserMusicsList, error) {
	out := new(UserMusicsList)
	err := c.cc.Invoke(ctx, "/proto.UsersMusics/GetMostViews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersMusicsServer is the server API for UsersMusics service.
type UsersMusicsServer interface {
	FollowArtist(context.Context, *FollowArtistRequest) (*Empty, error)
	UnfollowArtist(context.Context, *UnfollowArtistRequest) (*Empty, error)
	GetFollowingArtist(context.Context, *GetFollowingArtistRequest) (*FollowingArtist, error)
	GetAllFollowingArtists(context.Context, *GetAllFollowingArtistsRequest) (*FollowingArtists, error)
	ViewMusic(context.Context, *ViewMusicRequest) (*UserMusic, error)
	GetViews(context.Context, *GetViewsRequest) (*UserMusic, error)
	GetLastViews(context.Context, *GetLastViewsRequest) (*UserMusicsList, error)
	GetMostViews(context.Context, *GetMostViewsRequest) (*UserMusicsList, error)
}

// UnimplementedUsersMusicsServer can be embedded to have forward compatible implementations.
type UnimplementedUsersMusicsServer struct {
}

func (*UnimplementedUsersMusicsServer) FollowArtist(context.Context, *FollowArtistRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowArtist not implemented")
}
func (*UnimplementedUsersMusicsServer) UnfollowArtist(context.Context, *UnfollowArtistRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowArtist not implemented")
}
func (*UnimplementedUsersMusicsServer) GetFollowingArtist(context.Context, *GetFollowingArtistRequest) (*FollowingArtist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowingArtist not implemented")
}
func (*UnimplementedUsersMusicsServer) GetAllFollowingArtists(context.Context, *GetAllFollowingArtistsRequest) (*FollowingArtists, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFollowingArtists not implemented")
}
func (*UnimplementedUsersMusicsServer) ViewMusic(context.Context, *ViewMusicRequest) (*UserMusic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewMusic not implemented")
}
func (*UnimplementedUsersMusicsServer) GetViews(context.Context, *GetViewsRequest) (*UserMusic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViews not implemented")
}
func (*UnimplementedUsersMusicsServer) GetLastViews(context.Context, *GetLastViewsRequest) (*UserMusicsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastViews not implemented")
}
func (*UnimplementedUsersMusicsServer) GetMostViews(context.Context, *GetMostViewsRequest) (*UserMusicsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostViews not implemented")
}

func RegisterUsersMusicsServer(s *grpc.Server, srv UsersMusicsServer) {
	s.RegisterService(&_UsersMusics_serviceDesc, srv)
}

func _UsersMusics_FollowArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).FollowArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/FollowArtist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).FollowArtist(ctx, req.(*FollowArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersMusics_UnfollowArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).UnfollowArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/UnfollowArtist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).UnfollowArtist(ctx, req.(*UnfollowArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersMusics_GetFollowingArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).GetFollowingArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/GetFollowingArtist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).GetFollowingArtist(ctx, req.(*GetFollowingArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersMusics_GetAllFollowingArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFollowingArtistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).GetAllFollowingArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/GetAllFollowingArtists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).GetAllFollowingArtists(ctx, req.(*GetAllFollowingArtistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersMusics_ViewMusic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewMusicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).ViewMusic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/ViewMusic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).ViewMusic(ctx, req.(*ViewMusicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersMusics_GetViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).GetViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/GetViews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).GetViews(ctx, req.(*GetViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersMusics_GetLastViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).GetLastViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/GetLastViews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).GetLastViews(ctx, req.(*GetLastViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersMusics_GetMostViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersMusicsServer).GetMostViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersMusics/GetMostViews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersMusicsServer).GetMostViews(ctx, req.(*GetMostViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersMusics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UsersMusics",
	HandlerType: (*UsersMusicsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowArtist",
			Handler:    _UsersMusics_FollowArtist_Handler,
		},
		{
			MethodName: "UnfollowArtist",
			Handler:    _UsersMusics_UnfollowArtist_Handler,
		},
		{
			MethodName: "GetFollowingArtist",
			Handler:    _UsersMusics_GetFollowingArtist_Handler,
		},
		{
			MethodName: "GetAllFollowingArtists",
			Handler:    _UsersMusics_GetAllFollowingArtists_Handler,
		},
		{
			MethodName: "ViewMusic",
			Handler:    _UsersMusics_ViewMusic_Handler,
		},
		{
			MethodName: "GetViews",
			Handler:    _UsersMusics_GetViews_Handler,
		},
		{
			MethodName: "GetLastViews",
			Handler:    _UsersMusics_GetLastViews_Handler,
		},
		{
			MethodName: "GetMostViews",
			Handler:    _UsersMusics_GetMostViews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/users_musics_service.proto",
}
